### PR TITLE
C# Auth support docs

### PR DESCRIPTION
**Pull request by jtattermusch**
Tim, sums up what I have in terms of auth. Unlike ruby and node, I don't have a full flegded usable auth library yet, so I am wondering if this documentation should go in.

### CODE REVIEW

**Comment by tbetbetbe** [comment]
> Should we do this change in gRPC C#?

Yes, let's track whatever that's doing

**Comment by jtattermusch** [comment]
Should we merge this?

**Comment by tbetbetbe** [comment]
@LisaFC: FYI, we just updated the C# auth example

**Comment by LisaFC** [comment]
Ok, I'll take a look.

**Pull request merged**
