### PR TITLE
Change python route guide to proto3

### PR DESCRIPTION
**Pull request by LisaFC**
Changed the instructions to use the common proto3 route guide proto, removed the proto2 version.

### CODE REVIEW

**Comment by LisaFC** [comment]
@nathanielmanistaatgoogle, @tbetbetbe - PTAL

**Comment by nathanielmanistaatgoogle** [comment]
Change content looks good but the commit history looks weird - shouldn't this all be done in one commit? Please squash commits.

**Comment by nathanielmanistaatgoogle** [comment]
I've done the squash for you; please consider updating this pull request to be a merge of https://github.com/nathanielmanistaatgoogle/grpc-common/commit/53f8b2ac4535b3b74f07d80e40683a15d0b0380d?

**Comment by LisaFC** [comment]
Oh, thanks! I was just figuring out how to squash (for some reason the whole HEAD~4 notation for selecting commits wasn't working and git was attempting to rebase every commit since I created the repository). Dublin office was closed Friday/Monday so catching up now...

**Comment by LisaFC** [comment]
Argh, sorry, did something completely backwards and added more commits here
instead of removing them. I'm going to abandon this pull request and start
again.

On Tue, Apr 7, 2015 at 5:17 PM, googlebot <notifications@github.com> wrote:

> We found a Contributor License Agreement for you (the sender of this pull
> request) and all commit authors, but as best as we can tell these commits
> were authored by someone else. If that's the case, please add them to this
> pull request and have them confirm that they're okay with these commits
> being contributed to Google. If we're mistaken and you did author these
> commits, just reply here to confirm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc-common/pull/174#issuecomment-90628608>.
>



-- 
Google Ireland Ltd. : Registered in Ireland with company number 368047.
Gordon House, Barrow Street, Dublin 4, Ireland.

**Pull request closed without merging**
