### PR TITLE
Auth fixes

### PR DESCRIPTION
**Pull request by jboeuf**
@nathanielmanistaatgoogle @murgatroid99 @jtattermusch should have a look for changes to snippets in the different languages.
@a11r and @jayantkolhe may want to have a look as well for sanity check.

### CODE REVIEW

**Comment by nathanielmanistaatgoogle** [comment]
Neither this pull request nor your commit log messages describe the content of the change, which is that you're changing the example from a "user runs their own server and then runs their own client against their server" to "user runs their own server and then runs their own client against Google's public server". That's a pretty significant change, isn't it? I'm not pushing back against it but if that's what you intend you should describe it in more detail than just "Auth fixes".

(I have only reviewed the Python portion of these changes.)

**Comment by jboeuf** [comment]
Fair enough.

How about google credentials should ***never ever be used*** to connect to endpoints which are not Google owned as these may be stolen by malicious services and the replayed to impersonate clients to Google. 

The changes fix all the cases where we send google credentials to non-google owned endpoints.

**Comment by nathanielmanistaatgoogle** [comment]
Sounds good to me; thanks.

**Comment by jtattermusch** [comment]
LGTM for C#.

**Comment by nathanielmanistaatgoogle** [comment]
Change content looks fine for Python, but again please flesh out the commit log message to actually describe the content of the change? Also please squash commits.

**Comment by jboeuf** [comment]
@nathanielmanistaatgoogle Thanks for the feedback. Done.

**Comment by nathanielmanistaatgoogle** [comment]
LGTM and thank you for the fix.

If you wanted to fuss over your commit message just a little more you could modify it to conform to http://chris.beams.io/posts/git-commit/#seven-rules.

**Comment by jtattermusch** [comment]
Heads up:
In the meantime, the auth examples have been removed from grpc-common repo and they now live here
http://www.grpc.io/docs/guides/auth.html

Please everyone make sure to reflect changes suggested in this PR once updating docs for your language in grpc.io github pages repo.

**Pull request closed without merging**
