### PR TITLE
Fix grpc example after API changed

### PR DESCRIPTION
**Pull request by wilsonwen**

### CODE REVIEW

**Comment by ejona86** [comment]
Thanks for the PR, although we did need the CLA signed (and if you did sign it, then this comment should re-trigger the CLA bot). #168 just fixed the API usage (and documentation), but the "cd" thing may still be necessary.

**Comment by wilsonwen** [comment]
I have signed the CLA, please check it.

**Comment by yang-g** [comment]
I think the python part requires the document to be updated accordingly.

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the contribution. Please:
(1) remove python/helloworld.proto since it's no longer necessary,
(2) update the documentation, and
(3) squash commits so that every commit in the pull request is sensible.

**Comment by wilsonwen** [comment]
@nathanielmanistaatgoogle 
Please check, thanks.

**Comment by wilsonwen** [comment]
@nathanielmanistaatgoogle please check this

**Comment by nathanielmanistaatgoogle** [comment]
I think the change content looks good but it looks to me like you've still got more commits than you intend to have. In particular it's very weird to me to include merge commits in a pull request.

**Comment by wilsonwen** [comment]
Sorry, it takes me a while to figure out how to squash commits. Thank you.

**Comment by nathanielmanistaatgoogle** [comment]
Thanks for the contribution!

**Pull request merged**
