### PR TITLE
Fix path to grpc python virtualenv.

### PR DESCRIPTION
**Pull request by geekan**
It seems like that grpc has changed the virtualenv path.

### CODE REVIEW

**Comment by geekan** [comment]
I signed it!

**Comment by nathanielmanistaatgoogle** [comment]
I'm not seeing the path changed in my development environment (Goobuntu 14.04) - tell me more about yours?

**Comment by soltanmm** [comment]
@geekan Did you, by any chance, run the `tools/run_tests/build_python.sh` script manually...?

**Comment by geekan** [comment]
@soltanmm Yeah, I install it by grpc python [guide](https://github.com/grpc/grpc/blob/master/src/python/README.md), and I built python from source with `tools/run_tests/build_python.sh`.
Should I install it by `apt-get`?

**Comment by soltanmm** [comment]
@geekan It's not currently clear what the docs should be saying... For now, the incantation is `CONFIG=opt tools/run_tests/build_python.sh 2.7` following a `git submodule --init` and `make` of the repo. Alternatively, yeah, install the grpc package + pip Python package.

**Comment by geekan** [comment]
@soltanmm @nathanielmanistaatgoogle 
Many thanks for your replies!

**Pull request closed without merging**
